openapi: 3.0.0
info:
  description: API for SFS MS Chat Gateway
  version: "0.0.1"
  title: SFS MS Chat Gateway API
tags:
  - name: Accounts
    description: Accounts API
  - name: Channels
    description: Channels API
  - name: Messaging
    description: Messaging API
  - name: EMP
    description: EMP API
paths:
  /api/v1/internal/accounts:
    $ref: './paths/accounts.yaml#/accounts'
  /api/v1/internal/accounts/{federatedUserId}/emp/{emp}:
    $ref: './paths/accounts.yaml#/delete-account'
  /api/v1/internal/channels:
    $ref: './paths/channels.yaml#/channels'
  /api/v1/internal/channels/advisor/{advisorSymphonyId}/user/{federatedUserId}/emp/{emp}:
    $ref: './paths/channels.yaml#/manage-channel'
  /api/v1/internal/messages:
    $ref: './paths/messaging.yaml#/messages'
  /api/v1/internal/emps/reload:
    $ref: './paths/emps.yaml#/internal-reload-emps'
components:
  securitySchemes:
    sfsAuthentication:
      type: http
      scheme: bearer
      bearerFormat: jwt
