openapi: 3.0.0
info:
  description: API for SFS MS Chat Gateway
  version: "0.0.1"
  title: SFS MS Chat Gateway API
tags:
  - name: Accounts
    description: Accounts API
paths:
  /api/v1/internal/accounts:
    $ref: './paths/accounts.yaml#/accounts'
  /api/v1/internal/channels:
    $ref: './paths/channels.yaml#/channels'
  /api/v1/internal/channels/{symphonyId}/emp/{emp}:
    $ref: './paths/channels.yaml#/delete-by-symphonyId'
  /api/v1/internal/messages:
    $ref: './paths/messaging.yaml#/messages'
components:
  securitySchemes:
    sfsAuthentication:
      type: http
      scheme: bearer
      bearerFormat: jwt
