openapi: 3.0.0
info:
  description: API for SFS MS Chat Gateway
  version: "0.0.1"
  title: SFS MS Chat Gateway API
tags:
  - name: Accounts
    description: Accounts API
  - name: Channels
    description: Channels API
  - name: Messaging
    description: Messaging API
  - name: EMP
    description: EMP API
  - name: ModelGeneration
    description: Model Generation API
paths:
  /api/v1/internal/accounts:
    $ref: './paths/accounts.yaml#/accounts'
  /api/v1/internal/accounts/{federatedUserId}/emp/{emp}/deleteEMPAccount/{deleteEMPAccount}:
    $ref: './paths/accounts.yaml#/delete-account'
  /api/v1/internal/accounts/{federatedUserId}/emp/{emp}:
    $ref: './paths/accounts.yaml#/modify-account'
  /api/v1/internal/channels:
    $ref: './paths/channels.yaml#/channels'
  /api/v1/internal/channels/advisor/{advisorSymphonyId}/user/{federatedUserId}/emp/{emp}:
    $ref: './paths/channels.yaml#/retrieve-channel'
  /api/v1/internal/channels/delete:
    $ref: './paths/channels.yaml#/delete-channels'
  /api/v1/internal/messages:
    $ref: './paths/messaging.yaml#/messages'
  /api/v1/internal/system-messages:
    $ref: './paths/messaging.yaml#/system-messages'
  /api/v1/internal/emps/reload:
    $ref: './paths/emps.yaml#/internal-reload-emps'
  /api/v1/internal/rooms:
    $ref: './paths/room.yaml#/rooms'
  /api/v1/internal/rooms/{streamId}/members:
    $ref: './paths/room.yaml#/room-members'
  /api/v1/internal/rooms/{streamId}:
    $ref: './paths/room.yaml#/room'
  /api/v1/internal/connection-requests/{symphonyId}:
    $ref: './paths/connection-requests.yaml#/connection-requests'

  /model:
    $ref: './paths/utils.yaml#/model'
components:
  securitySchemes:
    sfsAuthentication:
      type: http
      scheme: bearer
      bearerFormat: jwt
