logging:
  level:
    com.symphony: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

aws:
  dynamodb:
    tableName: sfs-ms-chat-gateway
    endpoint: https://dynamodb.us-east-1.amazonaws.com
    signinRegion: us-east-1
  paramstore:
    prefix: /sfs
    name: ms-chat-gateway
  sqs:
    endpoint: https://sqs.us-east-1.amazonaws.com
    ingestion: sfs-dev-federation-events
    signinRegion: us-east-1

tds:
  hosts:
    '198': https://ces2-dev.symphony.com
    '196': https://ces3-dev.symphony.com

pod:
  id: 196
  url: https://ces3-dev.symphony.com
  sessionAuth: https://ces3-dev.symphony.com
  keyAuth: https://ces3-dev.symphony.com

bot:
  username: sfs-admin
  emailAddress: sfs-admin@symphony.com
  privateKey: file:certs/sfs-admin_privatekey.pem

agent:
  url: https://ces3-dev.symphony.com

microservices:
  WHATSAPP: 'https://federation-dev.symphony.com:9601'

microservice:
  chat:
    msAdminUrl: 'https://federation-dev.symphony.com:9600'
    sharedPublicKey: file:certs/sa_publickey.pem
    sharedPrivateKey: file:certs/sa_privatekey.pem
