aws:
  paramstore:
    enabled: false

tds:
  hosts:
    '198': https://ces2-dev.symphony.com
    '196': https://ces3-dev.symphony.com

pod:
  id: 196
  url: https://ces3-dev.symphony.com
  sessionAuth: https://ces3-dev.symphony.com
  keyAuth: https://ces3-dev.symphony.com

agent:
  url: https://ces3-dev.symphony.com

microservices:
  WHATSAPP: 'http://localhost:9601'

microservice:
  chat:
    msAdminUrl: 'http://localhost:9600'
