spring:
  application:
    name: sfs-ms-chat-gateway

extensionapp:
  id: com.symphony.sfs.admin-app

aws:
  dynamodb:
    tableName: sfs-ms-chat-gateway
    endpoint: http://localhost:4569 # localstack
    signinRegion: us-east-1
  sqs:
    endpoint: http://localhost:4576 # localstack
    signinRegion: us-east-1
    ingestion: sfs-federation-events
  paramstore:
    prefix: /sfs
    name: ms-chat-gateway

server:
  port: 9700
