spring:
  application:
    name: sfs-ms-chat-gateway
  sleuth:
    enabled: false
    # 128-Bits trace IDs is required for AWS X-Ray tracing
    trace-id128: true
    sampler:
      probability: 1.0
    opentracing:
      enabled: true
  cloud:
    discovery:
      enabled: false
  #    supports-join: true
  #    baggage-keys:
  #    propagation-keys:
  #    local-keys:

extensionapp:
  id: com.symphony.sfs.admin-app

microservice:
  chat:
    # SBE version at which we stop issuing IM
    stopImCreationAt: "20.10.1"

aws:
  dynamodb:
    tableName: sfs-ms-chat-gateway
    endpoint: http://localhost:4569 # localstack
    signinRegion: us-east-1
  sqs:
    endpoint: http://localhost:4576 # localstack
    signinRegion: us-east-1
    ingestion: sfs-federation-events
  paramstore:
    prefix: /sfs
    name: ms-chat-gateway
  sharedtable:
    name: sfs-ms-symphony
server:
  port: 9700

zipkin:
  reporter:
    enabled: false
    sender: http://127.0.0.1:9411/api/v2/spans
  sampler:
    strategy: always
    # used for brave.sampler.BoundarySampler, brave.sampler.CountingSampler (strategy = boundary, counting)
    probability: 1.0
    # used for brave.sampler.RateLimitingSampler (strategy = ratelimiting)
    tracesPerSecond: 10
  aws:
    reporter:
      enabled: true
  datadog:
    reporter:
      enabled: false

# SfsEventChecker configuration
eventchecker:
  scheduling:
    fixedDelay: 10m
    initialDelayMin: 1s
    initialDelayMax: 5s
